version: '3.8'

services:
  document-preview-editor:
    build: .
    container_name: document-preview-editor
    ports:
      - "${HOST_PORT:-5000}:${CONTAINER_PORT:-5000}"
    environment:
      - HOST=0.0.0.0
      - PORT=${CONTAINER_PORT:-5000}
      - DEBUG=${DEBUG:-False}
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY:-document-preview-editor-secret-key-2024}
    volumes:
      # 持久化上传和临时文件
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      # 可选：挂载配置文件（如果需要自定义配置）
      # - ./config.py:/app/config.py
    restart: unless-stopped
    networks:
      - document-preview-network

networks:
  document-preview-network:
    driver: bridge

# 使用示例:
# 1. 默认启动（端口5000）:
#    docker-compose up -d
#
# 2. 自定义端口启动:
#    HOST_PORT=8080 CONTAINER_PORT=5000 docker-compose up -d
#
# 3. 开发模式启动:
#    DEBUG=True FLASK_ENV=development docker-compose up -d
#
# 4. 使用环境变量文件:
#    创建 .env 文件并设置变量，然后运行 docker-compose up -d 